<?php $predmety = json_decode(file_get_contents('parts/subjects.json')); ?>

<option selected value = "Č"><?php echo $predmety->{"Č"}; ?></option>
<option value = "A/Bžk"><?php echo $predmety->{"A/Bžk"}; ?></option>
<option value = "A/Ju"><?php echo $predmety->{"A/Ju"}; ?></option>
<option value = "N/Cla"><?php echo $predmety->{"N/Cla"}; ?></option>
<option value = "N/Smě"><?php echo $predmety->{"N/Smě"}; ?></option>
<option value = "Š"><?php echo $predmety->{"Š"}; ?></option>
<option value = "Fr"><?php echo $predmety->{"Fr"}; ?></option>
<option value = "M"><?php echo $predmety->{"M"}; ?></option>
<option value = "F"><?php echo $predmety->{"F"}; ?></option>
<option value = "Bi"><?php echo $predmety->{"Bi"}; ?></option>
<option value = "Ch"><?php echo $predmety->{"Ch"}; ?></option>
<option value = "Z"><?php echo $predmety->{"Z"}; ?></option>
<option value = "D"><?php echo $predmety->{"D"}; ?></option>
<option value = "Sv"><?php echo $predmety->{"Sv"}; ?></option>
<option value = "In/Bla"><?php echo $predmety->{"In/Bla"}; ?></option>
<option value = "In/Hk"><?php echo $predmety->{"In/Hk"}; ?></option>
<option value = "In/Kre"><?php echo $predmety->{"In/Kre"}; ?></option>
<option value = "Hv"><?php echo $predmety->{"Hv"}; ?></option>
<option value = "Vv"><?php echo $predmety->{"Vv"}; ?></option>
<option value = "Tv"><?php echo $predmety->{"Tv"}; ?></option>
<option value = "X"><?php echo $predmety->{"X"}; ?></option>