							<option selected value = "Čj">Český jazyk</option>
							<option value = "Aj/Bž">Anglický jazyk - Blažková</option>
							<option value = "Aj/Ju">Anglický jazyk - Jugasová</option>
							<option value = "Nj/Cl">Německý jazyk - Clausová</option>
							<option value = "Nj/Sm">Německý jazyk - Smělíková</option>
							<option value = "Šj">Španělský jazyk</option>
							<option value = "Fj">Francouzský jazyk</option>
							<option value = "M">Matematika</option>
							<option value = "F">Fyzika</option>
							<option value = "Bi">Biologie</option>
							<option value = "Che">Chemie</option>
							<option value = "Z">Zeměpis</option>
							<option value = "D">Dějepis</option>
							<option value = "Sv">Společenské vědy</option>
							<option value = "Inf/Bl">Informatika - Blaha</option>
							<option value = "Inf/Hk">Informatika - Hájková</option>
							<option value = "Inf/Kr">Informatika - Krejčí</option>
							<option value = "Hv">Hudební výchova</option>
							<option value = "Vv">Výtvarná výchova</option>
							<option value = "Tv">Tělesná výchova</option>
							<option value = "X">Ostatní</option>
					